### ISSUE TITLE
IDE auto import issue

### ISSUE THREAD

**Issue by hanstf** [nsilly/exceptions#1]
### What are you doing?

I always use the auto import from the IDE (Webstorm) but whenever I use the auto-import, it will 
import the wrong package which is 
```
import { ExceptionHandler } from '@nsilly/exceptions/src/Exceptions/ExceptionHandler';
```
Instead of
```
import { ExceptionHandler } from '@nsilly/exceptions`;
```

### What do you expect to happen?

import the correct package

### Additional comment

I think by changing into 
```
export { ExceptionImpl as Exception } from './Exceptions/ExceptionImpl';
```
will fix the colliding name, but let me know what you are thinking.

**Comment by hieu-pv** [comment]
fixed in @nsilly/exceptions@4.0.3
